# Generated by Django 3.2.16 on 2022-12-04 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_alter_car_user'),
        ('common', '0004_auto_20221204_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_drive_date', models.DateField(default=datetime.datetime(2022, 12, 4, 13, 52, 28, 827649), verbose_name='Test drive date')),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
