# Generated by Django 3.2.16 on 2022-12-05 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_cartestdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartestdrive',
            name='test_drive_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 5, 20, 37, 9, 967381), verbose_name='Test drive date'),
        ),
    ]
