# Generated by Django 3.2.16 on 2022-12-05 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_cartestdrive_test_drive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartestdrive',
            name='test_drive_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 5, 20, 41, 28, 509251), verbose_name='Test drive date'),
        ),
    ]
