# Generated by Django 3.2.16 on 2022-12-05 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_cartestdrive_test_drive_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartestdrive',
            options={'ordering': ['test_drive_date']},
        ),
        migrations.AlterField(
            model_name='cartestdrive',
            name='test_drive_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 5, 21, 8, 39, 612730), verbose_name='Test drive date'),
        ),
    ]
