# Generated by Django 3.2.16 on 2022-12-07 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20221205_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartestdrive',
            name='test_drive_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 20, 41, 20, 131931), verbose_name='Test drive date'),
        ),
    ]
