# Generated by Django 3.2.16 on 2024-02-25 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_cartestdrive_test_drive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcomment',
            name='text',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cartestdrive',
            name='test_drive_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 10, 49, 45, 654023), verbose_name='Test drive date'),
        ),
    ]
